before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./ff
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - tap:
      owner: hyperledger-labs
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/hyperledger-labs/firefly-cli
    description: FireFly Command Line Interface (CLI)
    license: Apache-2.0
    dependencies:
      - name: go
        type: optional
      - name: docker
      - name: openssl
    install: |-
      bin.install "ff"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
